GET http://127.0.0.1:8000/api/comment
###
GET http://127.0.0.1:8000/api/comment/2
###
POST http://127.0.0.1:8000/api/comment
Content-Type: application/json
Accept: application/json

{
    "content":"day la data tao them",
    "song_id":"1",
    "user_id":"3" 
}

<!--xem lai phan tao. moi'-->

###
PATCH http://127.0.0.1:8000/api/comment/3
Content-Type: application/json
Accept: application/json

{
    "content":"day la data update",
    "song_id":"199",
    "user_id":"399" 
}
###
DELETE http://127.0.0.1:8000/api/comment/5
Content-Type: application/json
Accept: application/json