GET http://127.0.0.1:8000/api/notification
###
GET http://127.0.0.1:8000/api/notification/3
###
POST http://127.0.0.1:8000/api/notification
Content-Type: application/json

{
     
}
###
DELETE http://127.0.0.1:8000/api/notification/5
Content-Type: application/json
Accept: application/json