# get all playlist with related resource
GET http://127.0.0.1:8000/api/playlist/
Accept: application/json

###
# get all playlist with related resource
GET http://127.0.0.1:8000/api/playlist/11
Accept: application/json



###
#  get playlist with related resource
GET http://127.0.0.1:8000/api/playlist/11/relationships/songs

###
# update relationship 
PATCH http://127.0.0.1:8000/api/playlist/11/relationships/songs
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
