GET http://127.0.0.1:8000/api/song/
Accept: application/json


###
POST http://127.0.0.1:8000/api/song
Content-Type: application/json
Accept: application/json


{
    "name_song":"asdasd",
    "author":"qwer",
    "liked":"100",
    "views":"1000",
    "kind_music":"zxcv"

}
###
PATCH http://127.0.0.1:8000/api/song/2
Content-Type: application/json
Accept: application/json

{
    "name_song":"nhac",
    "liked":"900",
    "views":"999000",
    "category":"zxcv"

}
###
POST http://127.0.0.1:8000/api/authors
Content-Type: application/json

{
    
    "author":"asdasdasdasdsad",
    "email":"123456798@gmail.com"

}
###
DELETE http://127.0.0.1:8000/api/artist/3
Content-Type: application/json
Accept: application/json