# get song with playlist 
GET http://127.0.0.1:8000/api/song/1/relationships/playlist
Content-Type: application/json
Accept: application/json


###
# update song to playlist relationships 
PATCH  http://127.0.0.1:8000/api/song/1/relationships/playlist
content-type: application/json
accpet: application/json

{
    "id" : [
        "1", "2","3"
    ]
}


###
# update song with playlist 
PATCH  http://127.0.0.1:8000/api/song/1/relationships/playlist
content-type: application/json
accpet: application/json

{
    "id" : []
}


###
# get related resource with playlist 
GET  http://127.0.0.1:8000/api/song/1/playlist
content-type: application/json
accpet: application/json


###
# get related resource with playlist 
GET  http://127.0.0.1:8000/api/song?include=playlists
content-type: application/json
accpet: application/json

###
# get related resource with playlist 
GET  http://127.0.0.1:8000/api/song
content-type: application/json
accpet: application/json


###
# get related resource with playlist 
GET  http://127.0.0.1:8000/api/song?include=playlist
content-type: application/json
accpet: application/json





###
POST  http://127.0.0.1:8000/api/d
Content-Type: multipart/form-data;  boundary=----chickenHere
Accept: application/json


------chickenHere
Content-Disposition: form-data; name="audio"; filename="aa.mp3"
Content-Type: audio/mpeg3

< ./aa.mp3
------chickenHere
Content-Disposition: form-data; name="image"; filename="demo.jpg"
Content-Type: image/jpeg

< ./demo.jpg
------chickenHere--

###
POST  http://127.0.0.1:8000/api/song
Content-Type: multipart/form-data;  boundary=----chickenHere
accept: application/json

------chickenHere
Content-Disposition: form-data; name="name"; 
content-type: application/json

{
    "data" : {
      "attributes": {
        "name": "SIEU NHAN DIEN QUANG",
        "user_id" :"1"
      }
    }
}


------chickenHere
Content-Disposition: form-data; name="audio"; filename="aa.mp3"
Content-Type: audio/mpeg3

< ./aa.mp3
------chickenHere
Content-Disposition: form-data; name="image"; filename="demo.jpg"
Content-Type: image/jpeg

< ./demo.jpg
------chickenHere--


